sudo: required
services:
  - docker

before_install:
  - docker build -t gabrielfresco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gabrielfresco/react-test npm test -- --coverage

after_success:
   - docker build -t gabrielfresco/multi-client ./client
   - docker build -t gabrielfresco/multi-nginx ./nginx
   - docker build -t gabrielfresco/multi-server ./server
   - docker build -t gabrielfresco/multi-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push gabrielfresco/multi-client
   - docker push gabrielfresco/multi-nginx
   - docker push gabrielfresco/multi-server
   - docker push gabrielfresco/multi-worker
   
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-556169670639"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
